### ISSUE TITLE
image store

### ISSUE THREAD

**Issue by SpeckiJ** [GeoSopra2021/GISopraProject#1]
.
![20210907_111450](https://user-images.githubusercontent.com/13851077/132333973-577948de-dde6-4215-9352-93fce8ae6427.jpg)
![20210907_111516](https://user-images.githubusercontent.com/13851077/132333974-e40c4891-9e5a-4d4e-baab-cc9181c30d1c.jpg)

**Comment by Laxeros07** [comment]
![TrettiLogo](https://user-images.githubusercontent.com/90246149/132510061-0153dc74-775f-4c65-bd4d-8b73ce846946.png)
